#pragma once

#include "GL/glew.h"
#include <string>

namespace genesis {

class Texture {
private:
    GLuint textureId;
    int width, height;
    // TODO: figure out what this is actually for
    // (generated by stb, not sure what it does)
    int comp;
public:
    Texture(const std::string& image);
    ~Texture();

    int getWidth() { return width; }
    int getHeight() { return height; }
    GLuint getID() { return textureId; }
};

}
