fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        exclude: .clang-format
      - id: end-of-file-fixer
      - id: trailing-whitespace
