repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
        exclude: .clang-format
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: clang-format
        args: [-i, -style=file]
