name: Main workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pre-commit:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run hooks
        run: |
          python3 -m pip install pre-commit
          pre-commit run --all-files
  # TODO: tests? Dunno how, games aren't easily testable
