name: Main workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests:
    # TODO: set up a test matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
      - uses: LunarWatcher/install-conan@master
      - name: Preparation
        run: |
          sudo apt update
      - name: Run tests
        run: |
          conan config set tools.system.package_manager:mode=install
          mkdir build && cd build
          cmake ..
          make -j 4
          ./bin/tests
